import {
  createDoc, docToBuffer, header, footer, heading, keyValue, table,
  money, niceDate, rule, INK, MUTED, ACCENT, PAGE_MARGIN,
} from './base';

interface InvoiceLike {
  invoiceNumber: string;
  type: string;
  amount: number;
  gst: number;
  total: number;
  status: string;
  dueDate: string;
  description: string;
  createdAt?: string;
}

interface DealLike {
  clientName: string;
  clientEmail: string;
  clientPhone?: string;
}

/** Build a branded GST tax invoice PDF for a deal. */
export async function buildInvoicePdf(invoice: InvoiceLike, deal: DealLike): Promise<Buffer> {
  const doc = createDoc();
  header(doc, 'Tax Invoice');

  // Invoice meta + bill-to, two columns.
  const colY = doc.y;
  const colWidth = (doc.page.width - PAGE_MARGIN * 2) / 2;

  doc.fillColor(MUTED).font('Helvetica-Bold').fontSize(9).text('BILL TO', PAGE_MARGIN, colY);
  doc.fillColor(INK).font('Helvetica-Bold').fontSize(11).text(deal.clientName || '—');
  doc.font('Helvetica').fontSize(10).fillColor(MUTED).text(deal.clientEmail || '');
  if (deal.clientPhone) doc.text(deal.clientPhone);

  doc.fillColor(MUTED).font('Helvetica-Bold').fontSize(9).text('INVOICE', PAGE_MARGIN + colWidth, colY, { width: colWidth, align: 'right' });
  doc.fillColor(INK).font('Helvetica-Bold').fontSize(11).text(invoice.invoiceNumber || '—', PAGE_MARGIN + colWidth, doc.y, { width: colWidth, align: 'right' });
  doc.font('Helvetica').fontSize(9).fillColor(MUTED)
    .text(`Issued ${niceDate(invoice.createdAt || '')}`, { width: colWidth, align: 'right' })
    .text(`Due ${niceDate(invoice.dueDate)}`, { width: colWidth, align: 'right' })
    .text(`Status: ${invoice.status}`, { width: colWidth, align: 'right' });

  // Reset the cursor to the left margin: the right-aligned INVOICE column above
  // leaves it parked in the right column, which would shift the next section.
  doc.x = PAGE_MARGIN;
  doc.moveDown(2);

  heading(doc, 'Services');
  table(
    doc,
    [
      { header: 'Description', width: 0.6 },
      { header: 'Type', width: 0.18 },
      { header: 'Amount', width: 0.22, align: 'right' },
    ],
    [[invoice.description || 'Buyer agency services', invoice.type, money(invoice.amount)]],
  );

  // Totals block, right-aligned.
  const totalsX = doc.page.width - PAGE_MARGIN - 220;
  const lineW = 220;
  const totalLine = (label: string, value: string, bold = false) => {
    const font = bold ? 'Helvetica-Bold' : 'Helvetica';
    const size = bold ? 11 : 10;
    const y = doc.y;
    // Label (left) and value (right) share the same baseline; drawing them as
    // two separate full-width runs keeps the value flush-right without the
    // wrapping that `continued: true` + a narrow width causes.
    doc.font(font).fontSize(size).fillColor(bold ? INK : MUTED)
      .text(label, totalsX, y, { width: lineW, align: 'left' });
    doc.font(font).fontSize(size).fillColor(INK)
      .text(value, totalsX, y, { width: lineW, align: 'right' });
  };
  doc.moveDown(0.5);
  totalLine('Subtotal (excl. GST)', money(invoice.amount));
  totalLine('GST (15%)', money(invoice.gst));
  doc.moveDown(0.2);
  doc.strokeColor(ACCENT).lineWidth(1).moveTo(totalsX, doc.y).lineTo(totalsX + lineW, doc.y).stroke();
  doc.moveDown(0.3);
  totalLine('Total (incl. GST)', money(invoice.total), true);

  // The right-aligned totals leave the text cursor parked in the right column.
  // Reset it to the left margin so the Payment section flows full-width again.
  doc.x = PAGE_MARGIN;
  doc.moveDown(2);
  rule(doc);
  doc.moveDown(0.6);
  heading(doc, 'Payment');
  keyValue(doc, 'Terms', '7 working days from issue');
  doc.moveDown(0.3);
  doc.x = PAGE_MARGIN;
  doc.font('Helvetica').fontSize(9).fillColor(MUTED).text(
    'Please reference the invoice number with your payment. GST number and bank details are provided on the official statement. This document was generated by Martelli Buyers Agents.',
    PAGE_MARGIN,
    doc.y,
    { width: doc.page.width - PAGE_MARGIN * 2, align: 'left' },
  );

  footer(doc);
  return docToBuffer(doc);
}
